# Uncomment the next line to define a global platform for your project
platform :ios, '9.2'

target 'ProjectTransport' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectTransport
  pod 'SwiftyJSON', '2.4.0'

end
